### ISSUE TITLE
Show points per question

### ISSUE THREAD

**Issue by SeeeD** [timroes/lvlup-game#19]
It would be nice to see how much points I can make by answering this question correct. So the user can decide if he will answer "by random" or not..

**Comment by timroes** [comment]
I think a rating system like showing 1 to 3 icons for the exp range would be nice. I guess I would not show the exact amount of exp for the given question (to have a little bit of uncertainty in it, same why I don't want to show a live ranking on the screen).

**Comment by SeeeD** [comment]
Rating of the question (1 - 3) would be nice aswell. :+1:

**Comment by timroes** [comment]
Fixed in 38d3a48b2903142ac4f06a9923da2c454cbd2b32

A rating of 1 to 3 trophies will be shown above each question.
